# Generated by Django 3.0.4 on 2020-03-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('event_frequency', models.CharField(max_length=50)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_type', models.CharField(max_length=50)),
                ('event_speaker', models.CharField(max_length=50)),
                ('even_venue', models.CharField(max_length=100)),
                ('event_image', models.ImageField(upload_to='images/events/')),
            ],
        ),
        migrations.CreateModel(
            name='iqama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iq_fajr', models.CharField(max_length=50)),
                ('iq_dhur', models.CharField(max_length=50)),
                ('iq_asr', models.CharField(max_length=50)),
                ('iq_maghrib', models.CharField(max_length=50)),
                ('iq_isha', models.CharField(max_length=50)),
                ('iq_jumma', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prayer_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('Fajr_Salat', models.TimeField()),
                ('Sunrise_Time', models.TimeField()),
                ('Duhr_Salat', models.TimeField()),
                ('Asr_Salat', models.TimeField()),
                ('Maghrib_Salat', models.TimeField()),
                ('Isha_Salat', models.TimeField()),
            ],
        ),
    ]
